# Generated by Django 6.0.6 on 2026-06-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('sexe', models.CharField(max_length=100)),
            ],
        ),
    ]
