# Generated by Django 6.0.6 on 2026-06-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='sexe',
            field=models.CharField(choices=[('M', 'M.'), ('Mme', 'Mme')], max_length=3),
        ),
    ]
